stages:
  data_ingestion:
    cmd: python src/data_ingestion.py --dataset 
      sahilprajapati143/retail-analysis-large-dataset --output_dir data/raw
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw


  data_preprocessing:
    cmd: python src/data_preprocessing.py --in_dir data/raw --out_file 
      data/processed/monthly_data.csv
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed/monthly_data.csv
  feature_engineering:
    cmd: python src/features.py --input_file data/processed/monthly_data.csv --output_file data/processed/monthly_data_lags.csv --lags 1 2 3 4 6
    deps:
      - data/processed/monthly_data.csv
      - src/features.py
    outs:
      - data/processed/monthly_data_lags.csv

  train_model:
    cmd: python src/train_model.py --data data/processed/monthly_data_lags.csv 
      --params params.yaml
    deps:
    - data/processed/monthly_data_lags.csv
    - params.yaml
    - src/train_model.py
    outs:
    - models/model.pkl
  evaluate_model:
    cmd: python src/evaluate.py --model models/model.pkl --data 
      data/processed/monthly_data_lags.csv
    deps:
    - data/processed/monthly_data_lags.csv
    - models/model.pkl
    - src/evaluate.py
    outs:
    - metrics.json
