train:
  lags: [1, 2, 3, 4, 6]
  test_size: 0.3
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 7
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42

experiment:
  mlflow_tracking_uri: "file:./mlruns"
  mlflow_experiment: "monthly_demand_forecast"
